module.exports=[
    {
        id:1,
        restaurant_id:1,
        name:"kebab",
        price:50000,
    },
    {
        id:2,
        restaurant_id:1,
        name:"shishlik",
        price:60000,
    }, {
        id:3,
        restaurant_id:2,
        name:"kebab",
        price:10000,
    }, {
        id:4,
        restaurant_id:2,
        name:"kebsssab",
        price:40000,
    },
    {
        id:5,
        restaurant_id:2,
        name:"kebdddab",
        price:30000,
    },
]